### ISSUE TITLE
Grade calculated based on grades received, not all assignments

### ISSUE THREAD

**Issue by markfloryan** [markfloryan/ACAS#17]
Issue is that if node has two HWs, and only one is submitted, the grade for that node is calculated using just one assignment.

To help with this:
- Any gradescope assignment that exists but isn't in ACAS will be created automatically, then prof. can manually make connection to topic
- Make sure a zero is always set as student's grade otherwise (might already be happening).

**Comment by dwp7kp** [comment]
Grade is now calculated based on all assignments. As of now if an assignment doesn't have a grade it does not show up at all under the student's grade section. They do not have a zero, they just don't have an entry.

As for generating assignments, currently they are required to be linked to a topic so we would need another solution. Dummy node maybe?
