### ISSUE TITLE
Grade on main page currently shows a number (e.g., 62). Should show letter grade only (e.g., D) based on competency and mastery of nodes

### ISSUE THREAD

**Issue by markfloryan** [markfloryan/ACAS#9]
title says it all.

**Comment by dwp7kp** [comment]
**Branch:**
gradeDisplay

**Currently:**
Displays only a letter grade for students. Nothing for professors.

There is a bunch of code that handles the actual number grade. Should this be removed?

**Comment by dwp7kp** [comment]
done
